version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

 psql:
    image: postgres:11.9
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=codeany
      - POSTGRES_PASSWORD=pass1234
    network_mode: service:app

    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
